### ISSUE TITLE
add icons to a11y toolbar

### ISSUE THREAD

**Issue by bdolor** [BakingSoda/pressbooks#1]
The old plugin uses an image file `sprite.png` - I've only put in a placeholder for the toolbar area and icons need to be added. 

![screen shot 2015-02-10 at 4 24 52 pm](https://cloud.githubusercontent.com/assets/2048170/6139605/600ead78-b142-11e4-85ed-11bd0d314830.png)

You may want to take a look at Dashicons, which WP uses: https://developer.wordpress.org/resource/dashicons/

**Comment by ashzhang** [comment]
Icon added 
![screen shot 2015-02-13 at 2 19 31 pm](https://cloud.githubusercontent.com/assets/10442086/6196223/6836e376-b38b-11e4-9d03-4a7c0b8bb86b.png)
![screen shot 2015-02-13 at 2 17 10 pm](https://cloud.githubusercontent.com/assets/10442086/6196226/6b8564c6-b38b-11e4-815b-5871b4c76ad7.png)

**Comment by BakingSoda** [comment]
Icon added
![screen shot 2015-02-13 at 2 21 27 pm](https://cloud.githubusercontent.com/assets/10442086/6196254/ab7be5e6-b38b-11e4-814e-a7013c3e0e0b.png)
![screen shot 2015-02-13 at 2 21 17 pm](https://cloud.githubusercontent.com/assets/10442086/6196256/b09ec336-b38b-11e4-8e6f-6725140541a2.png)
