### ISSUE TITLE
css modifications on pdf export

### ISSUE THREAD

**Issue by bdolor** [BakingSoda/pressbooks#3]
styling in the css for pdf export intended to increase font size is currently missing some html elements on the export, such as the table of contents, headings, etc. Likely there are other html elements that have been missed, or require some adjustments, such as increasing line height. 

https://github.com/ashzhang/pressbooks/blob/accessibility/themes-book/pressbooks-book/functions.php#L1264

**Comment by bdolor** [comment]
since the latest commit, https://github.com/ashzhang/pressbooks/commit/0db3af8b120b2d2975041ab75a473aa05913b0aa some html elements still being excluded from an increase in font-size: 
- #half-title-page h1.title
- #copyright-page p
- h2.chapter-author
- body

**Comment by BakingSoda** [comment]
implemented
