### ISSUE TITLE
social media alignment messed up after toggle

### ISSUE THREAD

**Issue by BakingSoda** [BakingSoda/pressbooks#6]
![screen shot 2015-03-05 at 8 31 22 am](https://cloud.githubusercontent.com/assets/10442086/6509145/322928c0-c312-11e4-899d-a982f9c934d1.png)

**Comment by ashzhang** [comment]
Issue fixed
![screen shot 2015-03-05 at 8 31 37 am](https://cloud.githubusercontent.com/assets/10442086/6509150/3c7948e6-c312-11e4-8f88-12c1a74c5ef9.png)

**Comment by BakingSoda** [comment]
Issued fixed
![screen shot 2015-03-05 at 8 35 52 am](https://cloud.githubusercontent.com/assets/10442086/6509222/b5e43826-c312-11e4-882d-fed945149210.png)
